// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import FaqCenteredAccordion from './FaqCenteredAccordion';
import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	ContactForm,
	FaqCenteredAccordion,
	Image,
	Quote,
	Text,
};

export const components = {
	contact_form: ContactForm,
	faq_centered_accordion: FaqCenteredAccordion,
	image: Image,
	quote: Quote,
	text: Text,
};
